#!/usr/bin/env python3
import colorama, os
from colorama import  Fore, Back, Style
colorama.init()
print(Fore.RED)
print("#coded by pesimist")

os.system("figlet Kali Tools")


print("""

1) Kali Linux 20 Popüler  Araç


""")

islemno=input("İşlem Numarasını Giriniz : ")

if islemno=="1":

   tool=input("Devam Etmek İçin Enter Tuşuna Basınız : ")
   print("Kali Linux Popüler 20 Tool Karışık")
   os.system("sudo apt install metasploit-framework -y "+tool)
   os.system("sudo apt install nmap -y"+tool)
   os.system("sudo apt install wireshark -y"+tool)
   os.system("sudo apt install bettercap -y"+tool)
   os.system("sudo apt install ettercap -y"+tool)
   os.system("sudo apt install hping3 -y"+tool)
   os.system("sudo apt install sqlmap -y"+tool)
   os.system("sudo apt install aircrack-ng -y "+tool)
   os.system("sudo apt install maltego -y "+tool)
   os.system("sudo apt install burpsuite -y "+tool)
   os.system("sudo apt install macchanger -y "+tool)
   os.system("sudo apt install netcat -y "+tool)
   os.system("sudo apt install netdiscover -y "+tool)
   os.system("sudo apt install whois -y"+tool)
   os.system("sudo apt install john -y"+tool)
   os.system("sudo apt install hydra -y"+tool)
   os.system("sudo apt install dirb -y"+tool)
   os.system("sudo apt install recon-ng"+tool)
   os.system("sudo apt install sniffjoke -y"+tool)
   os.system("sudo apt install evilginx -y"+tool)

print("#coded by pesimist")
